### ISSUE TITLE
Possible Issue: Failing CRDT tests

### ISSUE THREAD

**Issue by iansmith** [basho/riak-ruby-client#154]
I am not sure what the status is of this library is with respect to Riak 2.0, so not sure if this is "expected."

I am running 2.0 PRE 11 and master of this library.  I am consistently failing the two test at the end of this ticket.  It _appears_ that it is passing a number of other CRDT tests, so the fact just these two fail seems odd.  Judging by the fetch message it looks like the PB expected response code isn't being returned.  

I am also having problems with CRDT sets in my own code, but that is possibly something I am doing wrong and this bug (?) is simpler to repro.

```
  1) CRDTs counters should allow batched counter ops
     Failure/Error: start = subject.value
     RuntimeError:
       Expected PBC DtFetchResp during CRDT fetch
     # ./lib/riak/client.rb:340:in `rescue in recover_from'
     # ./lib/riak/client.rb:312:in `recover_from'
     # ./lib/riak/client.rb:293:in `protobuffs'
     # ./lib/riak/crdt/base.rb:44:in `backend'
     # ./lib/riak/crdt/base.rb:48:in `loader'
     # ./lib/riak/crdt/base.rb:31:in `reload'
     # ./lib/riak/crdt/counter.rb:23:in `value'
     # ./spec/integration/riak/crdt_spec.rb:38:in `block (3 levels) in <top (required)>'

  2) CRDTs counters should allow straightforward counter ops
     Failure/Error: start = subject.value
     RuntimeError:
       Expected PBC DtFetchResp during CRDT fetch
     # ./lib/riak/client.rb:340:in `rescue in recover_from'
     # ./lib/riak/client.rb:312:in `recover_from'
     # ./lib/riak/client.rb:293:in `protobuffs'
     # ./lib/riak/crdt/base.rb:44:in `backend'
     # ./lib/riak/crdt/base.rb:48:in `loader'
     # ./lib/riak/crdt/base.rb:31:in `reload'
     # ./lib/riak/crdt/counter.rb:23:in `value'
     # ./spec/integration/riak/crdt_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 31.13 seconds
590 examples, 2 failures
```
